# Use the official Alpine Node.js base image
ARG BUILDER_IMAGE="node:@{NODE_VERSION}-alpine"

FROM ${BUILDER_IMAGE} as builder

WORKDIR /app

# Install Dependencies
COPY package.json package-lock.json ./
RUN npm install && npm cache clean --force --loglevel=error

# Build App
COPY src src
COPY *.json ./

RUN npm run prebuild
RUN npm run build

# Start the server using the production build
EXPOSE @{PORT}
CMD ["npm", "run", "start"]
