# Stage 0:
# --------

# Define base image
FROM oven/bun:@{BUN_VERSION}-alpine as base


# Stage 1:
# --------

FROM base AS build
WORKDIR /build
ENV NODE_ENV=production

# Install dependencies for production
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile --production

# Copy remaining files and build the app
COPY . .
RUN bun run build


# Stage 2:
# --------

FROM base AS release
WORKDIR /app

# Copy the built app and required files from previous stage
COPY --from=build /build/node_modules node_modules
COPY --from=build /build/package.json .
COPY --from=build /build/@{APP_ENTRYPOINT} .

USER bun
EXPOSE @{PORT}

# Start the app
ENTRYPOINT ["bun", "run", "@{APP_ENTRYPOINT}"]
